---
- hosts: all
  gather_facts: yes
  vars_files:
    - "vars/{{ ansible_distribution }}.yml"
  tasks:
  - name: general settings
    block:
    - name: install packages
      package:
        name: "{{ package_names }}"
        state: present
    - name: clean directories
      file:
        path: "{{ item }}"
        force: yes
        state: absent
      with_items: "{{ package_cleandir }}"
    - debug: var=timezone
    - name: change timezone setting
      file:
        src: "/usr/share/zoneinfo/{{ timezone }}"
        dest: /etc/localtime
        state: link
        force: yes
