---
- hosts: all
  gather_facts: yes
  vars_files:
    - "vars/{{ ansible_distribution }}.yml"
  tasks:
  - name: general settings
    block:
    - name: install packages
      package:
        name: "{{ package_names }}"
        state: present
    - name: clean directories
      file:
        path: "{{ item }}"
        force: yes
        state: absent
      with_items: "{{ package_cleandir }}"
    - debug: var=timezone
    - name: change timezone setting
      file:
        src: "/usr/share/zoneinfo/{{ timezone }}"
        dest: /etc/localtime
        state: link
        force: yes
  - name: smokeping configurations
    block:
    - name: generate httpd.conf
      template:
        src: "etc/nginx/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
    - name: generate smokeping config
      template:
        src: "etc/smokeping/config.j2"
        dest: "/etc/smokeping/config"
    - name: make smokeping directories
      file:
        path: "/var/lib/smokeping/{{ item }}"
        owner: nginx
        group: smokeping
        state: directory
      with_items:
        - cache
        - data
    - name: "make symlink to /dev/stdout"
      file:
        src: "/dev/stdout"
        dest: "/var/log/nginx/error.log"
        state: link
        follow: no
    - name: "make symlink to /dev/null"
      file:
        src: "/dev/null"
        dest: "/var/log/nginx/access.log"
        state: link
        follow: no
  - name: setup runit configrations
    block:
    - name: copy services directories
      copy:
        src: "services/"
        dest: "/services"
        owner: root
        group: root
        mode: 0755
    - name: set execute attribute
      file:
        path: "/services/{{ item }}/run"
      with_items:
        - "nginx"
        - "fcgiwrap"
        - "smokeping"
  - name: install probe tools
    get_url:
      url: http://www.vdberg.org/~richard/tcpping
      dest: /usr/local/bin/tcpping
      mode: '0755'
